# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  
  - name: Research Overview
    url: '#overview'
    weight: 20
  - name: Current Projects
    url: '#current'
    weight: 30
  - identifer = "team"
    name: Research Team
    url: '#team'
    weight: 40
  - identifier = "students"
    name: UO PhD students
    url: "/students"
    parent: "team"
    weight: 1
  - identifier = "affiliated"
    name: Affiliated PhD students
    url: "/affiliated"
    parent: "team"
    weight: 2
  - name: 2025 Applicants
    url: '#applicants'
    weight: 41
  - name: Commitment to DEI
    url: '#dei'
    weight: 50
  - name: Resources
    url: '#resources'
    weight: 60
  - name: Bonus Content - Lab Pets!
    url: '#pets'
    weight: 70
  - name: CV
    url: 'uploads/resume.pdf'
    weight: 80
 



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
